#!/usr/bin/env python
from argparse import ArgumentParser

from transformer.commands.convert import ConvertCommand
from transformer.commands.download import DownloadCommand
from transformer.commands.env import EnvironmentCommand
from transformer.commands.run import RunCommand
from transformer.commands.serving import ServeCommand
from transformer.commands.user import UserCommands

if __name__ == '__main__':
    parser = ArgumentParser('Transformers CLI tool', usage='transformer-cli <command> [<args>]')
    commands_parser = parser.add_subparsers(help='transformer-cli command helpers')

    # Register commands
    ConvertCommand.register_subcommand(commands_parser)
    DownloadCommand.register_subcommand(commands_parser)
    EnvironmentCommand.register_subcommand(commands_parser)
    RunCommand.register_subcommand(commands_parser)
    ServeCommand.register_subcommand(commands_parser)
    UserCommands.register_subcommand(commands_parser)

    # Let's go
    args = parser.parse_args()

    if not hasattr(args, 'func'):
        parser.print_help()
        exit(1)

    # Run
    service = args.func(args)
    service.run()
